// web/src/components/ui/input.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        'flex h-10 w-full min-w-0 rounded-[var(--r-thumb)] border border-[var(--hairline)] bg-surface px-3 py-1 text-[14px] text-foreground transition-[border-color,box-shadow,background-color] duration-200 ease-[var(--ease-out-quart)] outline-none',
        'placeholder:text-[var(--text-4)] selection:bg-[rgba(0,113,227,0.18)]',
        'hover:bg-hover',
        'focus-visible:border-[var(--accent)] focus-visible:bg-surface focus-visible:shadow-[0_0_0_4px_rgba(0,113,227,0.18)] dark:focus-visible:shadow-[0_0_0_4px_rgba(10,132,255,0.28)]',
        'aria-invalid:border-destructive aria-invalid:shadow-[0_0_0_4px_rgba(215,0,21,0.14)]',
        'file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-[13px] file:font-medium file:text-foreground',
        'disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-40',
        className,
      )}
      {...props}
    />
  )
}

export { Input }

// web/src/components/ui/Input.vue
<script setup lang="ts">
import { useClass } from '@/lib/utils'

const props = withDefaults(
  defineProps<{
    modelValue?: string | number
    type?: string
    placeholder?: string
    id?: string
    disabled?: boolean
    invalid?: boolean
    maxLength?: number
    min?: number
    max?: number
    autoFocus?: boolean
    autoComplete?: string
    spellCheck?: boolean
  }>(),
  {
    modelValue: '',
    type: 'text',
    placeholder: '',
    id: '',
    disabled: false,
    invalid: false,
    maxLength: undefined,
    min: undefined,
    max: undefined,
    autoFocus: false,
    autoComplete: undefined,
    spellCheck: undefined,
  },
)

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()

const classes = useClass('input', props.invalid && 'input--invalid')

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).value)
}
</script>

<template>
  <input
    :id="id"
    :type="type"
    :placeholder="placeholder"
    :disabled="disabled"
    :maxlength="maxLength"
    :min="min"
    :max="max"
    :autofocus="autoFocus"
    :autocomplete="autoComplete"
    :spellcheck="spellCheck"
    :value="modelValue"
    :class="classes"
    :aria-invalid="invalid || undefined"
    @input="onInput"
  />
</template>

<style scoped>
.input {
  display: flex;
  height: 40px;
  width: 100%;
  min-width: 0;
  border-radius: var(--r-thumb);
  border: 1px solid var(--hairline);
  background: var(--surface);
  padding: 0 12px;
  font-size: 14px;
  color: var(--text);
  outline: none;
  transition:
    border-color 200ms var(--ease-out-quart),
    box-shadow 200ms var(--ease-out-quart),
    background-color 200ms var(--ease-out-quart);
}
.input::placeholder {
  color: var(--text-4);
}
.input::selection {
  background: rgba(0, 113, 227, 0.18);
}
.input:hover:not(:focus):not(:disabled) {
  background: var(--hover);
}
.input:focus {
  border-color: var(--accent);
  background: var(--surface);
  box-shadow: 0 0 0 4px rgba(0, 113, 227, 0.18);
}
.dark .input:focus {
  box-shadow: 0 0 0 4px rgba(10, 132, 255, 0.28);
}
.input--invalid {
  border-color: var(--danger);
  box-shadow: 0 0 0 4px rgba(215, 0, 21, 0.14);
}
.input:disabled {
  pointer-events: none;
  cursor: not-allowed;
  opacity: 0.4;
}
.input[type='file'] {
  display: inline-flex;
  height: 28px;
  border: 0;
  background: transparent;
  font-size: 13px;
  font-weight: 500;
  color: var(--text);
}
</style>
