// web/src/components/ui/Switch.vue
<script setup lang="ts">
import { useClass } from '@/lib/utils'

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    id?: string
    disabled?: boolean
  }>(),
  {
    modelValue: false,
    id: '',
    disabled: false,
  },
)

const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>()

const classes = useClass('switch')

function onClick() {
  if (props.disabled) return
  emit('update:modelValue', !props.modelValue)
}
</script>

<template>
  <button
    :id="id"
    type="button"
    role="switch"
    :aria-checked="modelValue"
    :class="classes"
    :disabled="disabled"
    @click="onClick"
  >
    <span class="switch__thumb" />
  </button>
</template>

<style scoped>
.switch {
  position: relative;
  display: inline-flex;
  width: 51px;
  height: 31px;
  flex-shrink: 0;
  align-items: center;
  border-radius: 999px;
  background: var(--track);
  outline: none;
  cursor: pointer;
  transition: background-color 300ms var(--ease-out-quart);
  -webkit-tap-highlight-color: transparent;
}
.switch::before {
  content: '';
  position: absolute;
  inset: -6.5px 0;
}
.switch[aria-checked='true'] {
  background: var(--live);
}
.switch:disabled {
  cursor: not-allowed;
  opacity: 0.4;
}
.switch:focus-visible {
  box-shadow: 0 0 0 4px rgba(0, 113, 227, 0.25);
}
.dark .switch:focus-visible {
  box-shadow: 0 0 0 4px rgba(10, 132, 255, 0.35);
}

.switch__thumb {
  display: block;
  width: 27px;
  height: 27px;
  border-radius: 999px;
  background: #fff;
  box-shadow:
    0 2px 6px rgba(0, 0, 0, 0.18),
    0 0 0 0.5px rgba(0, 0, 0, 0.04);
  transition:
    transform 300ms var(--ease-spring),
    background-color 200ms var(--ease-smooth);
}
.switch[aria-checked='true'] .switch__thumb {
  transform: translateX(22px);
}
.switch[aria-checked='false'] .switch__thumb {
  transform: translateX(2px);
}
</style>

// web/src/components/ui/switch.tsx
import * as React from 'react'
import * as SwitchPrimitive from '@radix-ui/react-switch'
import { cn } from '@/lib/utils'

function Switch({
  className,
  ...props
}: React.ComponentProps<typeof SwitchPrimitive.Root>) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      className={cn(
        'peer relative inline-flex h-[31px] w-[51px] shrink-0 items-center rounded-full transition-colors duration-300 ease-[var(--ease-out-quart)] outline-none',
        'data-[state=checked]:bg-[var(--live)] data-[state=unchecked]:bg-[var(--track)]',
        'disabled:cursor-not-allowed disabled:opacity-40',
        // 44px hit area without a visual 44px box
        'before:absolute before:-inset-y-[6.5px] before:-inset-x-0 before:content-[""]',
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(
          'pointer-events-none block size-[27px] rounded-full bg-white shadow-[0_2px_6px_rgba(0,0,0,0.18),0_0_0_0.5px_rgba(0,0,0,0.04)] transition-transform duration-300 ease-[var(--ease-spring)]',
          'data-[state=checked]:translate-x-[22px] data-[state=unchecked]:translate-x-[2px]',
        )}
      />
    </SwitchPrimitive.Root>
  )
}

export { Switch }
