// web/src/components/ui/textarea.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

function Textarea({ className, ...props }: React.ComponentProps<'textarea'>) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        'flex field-sizing-content min-h-20 w-full rounded-[var(--r-thumb)] border border-[var(--hairline)] bg-surface px-3 py-2.5 text-[14px] leading-relaxed text-foreground transition-[border-color,box-shadow,background-color] duration-200 ease-[var(--ease-out-quart)] outline-none',
        'placeholder:text-[var(--text-4)]',
        'hover:bg-hover',
        'focus-visible:border-[var(--accent)] focus-visible:bg-surface focus-visible:shadow-[0_0_0_4px_rgba(0,113,227,0.18)] dark:focus-visible:shadow-[0_0_0_4px_rgba(10,132,255,0.28)]',
        'aria-invalid:border-destructive aria-invalid:shadow-[0_0_0_4px_rgba(215,0,21,0.14)]',
        'resize-none disabled:cursor-not-allowed disabled:opacity-40',
        className,
      )}
      {...props}
    />
  )
}

export { Textarea }

// web/src/components/ui/Textarea.vue
<script setup lang="ts">
import { useClass } from '@/lib/utils'

const props = withDefaults(
  defineProps<{
    modelValue?: string
    placeholder?: string
    id?: string
    rows?: number
    disabled?: boolean
    invalid?: boolean
  }>(),
  {
    modelValue: '',
    placeholder: '',
    id: '',
    rows: 3,
    disabled: false,
    invalid: false,
  },
)

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()

const classes = useClass('textarea', props.invalid && 'textarea--invalid')

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLTextAreaElement).value)
}
</script>

<template>
  <textarea
    :id="id"
    :placeholder="placeholder"
    :rows="rows"
    :disabled="disabled"
    :value="modelValue"
    :class="classes"
    :aria-invalid="invalid || undefined"
    @input="onInput"
  />
</template>

<style scoped>
.textarea {
  display: flex;
  width: 100%;
  min-height: 80px;
  border-radius: var(--r-thumb);
  border: 1px solid var(--hairline);
  background: var(--surface);
  padding: 10px 12px;
  font-size: 14px;
  line-height: 1.6;
  color: var(--text);
  outline: none;
  resize: none;
  transition:
    border-color 200ms var(--ease-out-quart),
    box-shadow 200ms var(--ease-out-quart),
    background-color 200ms var(--ease-out-quart);
}
.textarea::placeholder {
  color: var(--text-4);
}
.textarea:hover:not(:focus):not(:disabled) {
  background: var(--hover);
}
.textarea:focus {
  border-color: var(--accent);
  background: var(--surface);
  box-shadow: 0 0 0 4px rgba(0, 113, 227, 0.18);
}
.dark .textarea:focus {
  box-shadow: 0 0 0 4px rgba(10, 132, 255, 0.28);
}
.textarea--invalid {
  border-color: var(--danger);
  box-shadow: 0 0 0 4px rgba(215, 0, 21, 0.14);
}
.textarea:disabled {
  cursor: not-allowed;
  opacity: 0.4;
}
</style>
