// web/src/components/teachers/TeacherFilters.tsx
import { Download, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

export interface TeacherFilterValues {
  keyword: string
  subject: string
  gender: '' | 'male' | 'female'
  education: string
  hasCert: '' | '0' | '1'
}

const ALL = '__all__'

export default function TeacherFilters({
  keyword,
  onKeywordChange,
  subjects,
  educations,
  values,
  onChange,
  onExport,
  exporting,
}: {
  keyword: string
  onKeywordChange: (v: string) => void
  subjects: string[]
  educations: string[]
  values: Omit<TeacherFilterValues, 'keyword'>
  onChange: (next: Partial<Omit<TeacherFilterValues, 'keyword'>>) => void
  onExport: () => void
  exporting: boolean
}) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <div className="relative min-w-[220px] flex-1 sm:flex-none">
        <Search
          className="absolute top-1/2 left-3 size-[18px] -translate-y-1/2 text-[var(--text-3)]"
          strokeWidth={1.75}
        />
        <Input
          className="w-full pl-10 sm:w-64"
          placeholder="搜索姓名"
          value={keyword}
          onChange={(e) => onKeywordChange(e.target.value)}
        />
      </div>

      <Select value={values.subject || ALL} onValueChange={(v) => onChange({ subject: v === ALL ? '' : v })}>
        <SelectTrigger className="w-36"><SelectValue placeholder="全部学科" /></SelectTrigger>
        <SelectContent>
          <SelectItem value={ALL}>全部学科</SelectItem>
          {subjects.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
        </SelectContent>
      </Select>

      <Select value={values.gender || ALL} onValueChange={(v) => onChange({ gender: (v === ALL ? '' : v) as '' | 'male' | 'female' })}>
        <SelectTrigger className="w-32"><SelectValue placeholder="性别" /></SelectTrigger>
        <SelectContent>
          <SelectItem value={ALL}>全部性别</SelectItem>
          <SelectItem value="male">男</SelectItem>
          <SelectItem value="female">女</SelectItem>
        </SelectContent>
      </Select>

      <Select value={values.education || ALL} onValueChange={(v) => onChange({ education: v === ALL ? '' : v })}>
        <SelectTrigger className="w-32"><SelectValue placeholder="学历" /></SelectTrigger>
        <SelectContent>
          <SelectItem value={ALL}>全部学历</SelectItem>
          {educations.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
        </SelectContent>
      </Select>

      <Select value={values.hasCert || ALL} onValueChange={(v) => onChange({ hasCert: (v === ALL ? '' : v) as '' | '0' | '1' })}>
        <SelectTrigger className="w-36"><SelectValue placeholder="教师资格证" /></SelectTrigger>
        <SelectContent>
          <SelectItem value={ALL}>资格证不限</SelectItem>
          <SelectItem value="1">有资格证</SelectItem>
          <SelectItem value="0">无资格证</SelectItem>
        </SelectContent>
      </Select>

      <Button variant="outline" onClick={onExport} loading={exporting}>
        {!exporting && <Download />}导出 Excel
      </Button>
    </div>
  )
}

// web/src/components/teachers/TeacherFilters.vue
<script setup lang="ts">
import { Download, Search } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Select from '@/components/ui/Select.vue'
import SelectItem from '@/components/ui/SelectItem.vue'

export interface TeacherFilterValues {
  keyword: string
  subject: string
  gender: '' | 'male' | 'female'
  education: string
  hasCert: '' | '0' | '1'
}

const ALL = '__all__'

defineProps<{
  keyword: string
  subjects: string[]
  educations: string[]
  values: Omit<TeacherFilterValues, 'keyword'>
  exporting: boolean
}>()

const emit = defineEmits<{
  'update:keyword': [value: string]
  change: [next: Partial<Omit<TeacherFilterValues, 'keyword'>>]
  export: []
}>()
</script>

<template>
  <div class="filters">
    <div class="filters__search">
      <Search :size="18" :stroke-width="1.75" class="filters__search-icon" />
      <Input
        class="filters__search-input"
        placeholder="搜索姓名"
        :model-value="keyword"
        @update:model-value="emit('update:keyword', $event)"
      />
    </div>

    <Select
      :model-value="values.subject || ALL"
      class="filters__select filters__select--subject"
      @update:model-value="emit('change', { subject: $event === ALL ? '' : $event })"
    >
      <template #value="{ selected }">
        {{ selected === ALL ? '全部学科' : selected }}
      </template>
      <SelectItem :value="ALL">全部学科</SelectItem>
      <SelectItem v-for="s in subjects" :key="s" :value="s">{{ s }}</SelectItem>
    </Select>

    <Select
      :model-value="values.gender || ALL"
      class="filters__select filters__select--gender"
      @update:model-value="
        emit('change', { gender: ($event === ALL ? '' : $event) as '' | 'male' | 'female' })
      "
    >
      <template #value="{ selected }">
        {{ selected === ALL ? '性别' : selected === 'male' ? '男' : '女' }}
      </template>
      <SelectItem :value="ALL">全部性别</SelectItem>
      <SelectItem value="male">男</SelectItem>
      <SelectItem value="female">女</SelectItem>
    </Select>

    <Select
      :model-value="values.education || ALL"
      class="filters__select filters__select--education"
      @update:model-value="emit('change', { education: $event === ALL ? '' : $event })"
    >
      <template #value="{ selected }">
        {{ selected === ALL ? '学历' : selected }}
      </template>
      <SelectItem :value="ALL">全部学历</SelectItem>
      <SelectItem v-for="s in educations" :key="s" :value="s">{{ s }}</SelectItem>
    </Select>

    <Select
      :model-value="values.hasCert || ALL"
      class="filters__select filters__select--cert"
      @update:model-value="
        emit('change', { hasCert: ($event === ALL ? '' : $event) as '' | '0' | '1' })
      "
    >
      <template #value="{ selected }">
        {{
          selected === ALL
            ? '教师资格证'
            : selected === '1'
              ? '有资格证'
              : '无资格证'
        }}
      </template>
      <SelectItem :value="ALL">资格证不限</SelectItem>
      <SelectItem value="1">有资格证</SelectItem>
      <SelectItem value="0">无资格证</SelectItem>
    </Select>

    <Button variant="outline" :loading="exporting" @click="emit('export')">
      <template v-if="!exporting"><Download :size="18" /></template>
      导出 Excel
    </Button>
  </div>
</template>

<style scoped>
.filters {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.5rem;
}

.filters__search {
  position: relative;
  min-width: 220px;
  flex: 1;
}
@media (min-width: 640px) {
  .filters__search {
    flex: none;
  }
}
.filters__search-icon {
  position: absolute;
  top: 50%;
  left: 12px;
  transform: translateY(-50%);
  color: var(--text-3);
  pointer-events: none;
}
.filters__search-input {
  padding-left: 40px;
  width: 100%;
}
@media (min-width: 640px) {
  .filters__search-input {
    width: 256px;
  }
}

.filters__select--subject {
  width: 144px;
}
.filters__select--gender {
  width: 128px;
}
.filters__select--education {
  width: 128px;
}
.filters__select--cert {
  width: 144px;
}
</style>
