// web/src/pages/TeacherList.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Pencil, Plus, Trash2 } from 'lucide-vue-next'
import {
  batchDeleteTeachers,
  createTeacher,
  deleteTeacher,
  exportXlsx,
  fetchTeacher,
  fetchTeachers,
  updateTeacher,
  ageOrDash,
  genderLabel,
  type ListParams,
  type Teacher,
  type TeacherInput,
} from '@/api/teachers'
import { fetchDictionaries, type Dictionary } from '@/api/dicts'
import TeacherFilters, { type TeacherFilterValues } from '@/components/teachers/TeacherFilters.vue'
import TeacherFormDialog from '@/components/teachers/TeacherFormDialog.vue'
import Button from '@/components/ui/Button.vue'
import DataTable, { type Column } from '@/components/DataTable.vue'
import PaginationBar from '@/components/PaginationBar.vue'
import PageHeader from '@/components/PageHeader.vue'
import DeleteConfirm from '@/components/DeleteConfirm.vue'
import { useQuery, useMutation, invalidateQueries } from '@/composables/useQuery'
import { useToast } from '@/composables/useToast'
import { cn, categoryTint, errMsg } from '@/lib/utils'

const PAGE_SIZE = 20

const route = useRoute()
const router = useRouter()
const { success, error } = useToast()

const urlKeyword = typeof route.query.keyword === 'string' ? route.query.keyword : ''
const keyword = ref(urlKeyword)
const debounced = ref(urlKeyword)
const subject = ref(typeof route.query.subject === 'string' ? route.query.subject : '')
const gender = ref<'' | 'male' | 'female'>(
  (typeof route.query.gender === 'string' ? route.query.gender : '') as '' | 'male' | 'female',
)
const education = ref(typeof route.query.education === 'string' ? route.query.education : '')
const hasCert = ref<'' | '0' | '1'>(
  (typeof route.query.hasCert === 'string' ? route.query.hasCert : '') as '' | '0' | '1',
)
const selected = ref<(string | number)[]>([])
const page = ref(1)
const exporting = ref(false)

// 新增 / 编辑弹窗：id 为 undefined 表示新增
const dialogOpen = ref(false)
const editingId = ref<number | null>(null)

// 关键字防抖 300ms
let debounceTimer: ReturnType<typeof setTimeout> | null = null
watch(keyword, (v) => {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    debounced.value = v
  }, 300)
})

// 关键字与筛选同步到 URL，刷新/分享后条件不丢
watch([debounced, subject, gender, education, hasCert], () => {
  const q: Record<string, string> = {}
  if (debounced.value.trim()) q.keyword = debounced.value.trim()
  if (subject.value) q.subject = subject.value
  if (gender.value) q.gender = gender.value
  if (education.value) q.education = education.value
  if (hasCert.value) q.hasCert = hasCert.value
  void router.replace({ query: q })
})

// 筛选变化清空多选
watch([debounced, subject, gender, education, hasCert, page], () => {
  selected.value = []
})

const { data: subjects } = useQuery<Dictionary[]>(['dicts', 'subject'], () =>
  fetchDictionaries('subject'),
)
const { data: educations } = useQuery<Dictionary[]>(['dicts', 'education'], () =>
  fetchDictionaries('education'),
)

const subjectColor = computed(() => {
  const m: Record<string, string> = {}
  for (const d of subjects.value ?? []) if (d.color) m[d.name] = d.color
  return m
})

const listParams = computed<ListParams>(() => ({
  keyword: debounced.value.trim() || undefined,
  subject: subject.value || undefined,
  gender: gender.value || undefined,
  education: education.value || undefined,
  hasCert: (hasCert.value === '' ? '' : Number(hasCert.value)) as '' | 0 | 1,
}))

const { data, isLoading, refetch } = useQuery(
  ['teachers', listParams.value, page.value],
  () => fetchTeachers({ ...listParams.value, page: page.value, size: PAGE_SIZE }),
)

const { data: editing } = useQuery<Teacher>(
  ['teachers', editingId.value],
  () => fetchTeacher(editingId.value as number),
  { enabled: computed(() => editingId.value !== null) },
)

const refresh = () => {
  void refetch()
  invalidateQueries(['teachers'])
}

const createMutation = useMutation(createTeacher)
const updateMutation = useMutation(({ id, data }: { id: number; data: TeacherInput }) =>
  updateTeacher(id, data),
)
const formSubmitting = computed(() => createMutation.isPending.value || updateMutation.isPending.value)
const deleteMutation = useMutation(deleteTeacher)

const onExport = async () => {
  exporting.value = true
  try {
    await exportXlsx(listParams.value)
    success('已导出 Excel')
  } catch (e) {
    error(errMsg(e, '导出失败'))
  } finally {
    exporting.value = false
  }
}

const openCreate = () => {
  editingId.value = null
  dialogOpen.value = true
}

const openEdit = (id: number) => {
  editingId.value = id
  dialogOpen.value = true
}

const columns: Column[] = [
  { title: '姓名', key: 'name', width: 120 },
  { title: '性别', key: 'gender', width: 70 },
  { title: '年龄', key: 'age', width: 70 },
  { title: '学科', key: 'subject', width: 110 },
  { title: '资格证', key: 'has_cert', width: 80 },
  { title: '联系电话', key: 'phone', width: 130 },
  { title: '学历', key: 'education', width: 90 },
  { title: '毕业院校', key: 'university' },
  { title: '专业', key: 'major' },
  { title: '录入时间', key: 'created_at', width: 150 },
  { title: '操作', key: 'action', width: 120 },
]

const onFilterChange = (next: Partial<Omit<TeacherFilterValues, 'keyword'>>) => {
  if (next.subject !== undefined) subject.value = next.subject
  if (next.gender !== undefined) gender.value = next.gender
  if (next.education !== undefined) education.value = next.education
  if (next.hasCert !== undefined) hasCert.value = next.hasCert
  page.value = 1
}

const onSubmitDialog = async (input: TeacherInput) => {
  if (editingId.value) {
    try {
      await updateMutation.mutate({ id: editingId.value, data: input })
      success('已保存')
      dialogOpen.value = false
      editingId.value = null
      refresh()
    } catch (e) {
      error(errMsg(e, '保存失败'))
    }
  } else {
    try {
      await createMutation.mutate(input)
      success('已创建')
      dialogOpen.value = false
      refresh()
    } catch (e) {
      error(errMsg(e, '创建失败'))
    }
  }
}

const onDelete = async (id: number) => {
  try {
    await deleteMutation.mutate(id)
    success('已删除')
    if ((data.value?.items.length ?? 0) === 1 && page.value > 1) page.value -= 1
    else refresh()
  } catch (e) {
    error(errMsg(e, '删除失败'))
  }
}

const onBatchDelete = async () => {
  try {
    const n = await batchDeleteTeachers(selected.value.map(Number))
    success(`已删除 ${n} 条记录`)
    selected.value = []
    refresh()
  } catch (e) {
    error(errMsg(e, '批量删除失败'))
  }
}
</script>

<template>
  <div class="teacher-list">
    <PageHeader title="人员管理" description="学校教师与工作人员档案">
      <template #action>
        <Button @click="openCreate"><Plus :size="18" /> 新增人员</Button>
      </template>
    </PageHeader>

    <TeacherFilters
      :keyword="keyword"
      :subjects="(subjects ?? []).filter((d) => d.enabled === 1).map((d) => d.name)"
      :educations="(educations ?? []).filter((d) => d.enabled === 1).map((d) => d.name)"
      :values="{ subject, gender, education, hasCert }"
      :exporting="exporting"
      @update:keyword="(v) => { keyword = v; page = 1 }"
      @change="onFilterChange"
      @export="onExport"
    />

    <div v-if="selected.length > 0" class="teacher-list__selection surface-card">
      <span class="teacher-list__selection-count">已选 {{ selected.length }} 条</span>
      <DeleteConfirm
        title="批量删除"
        :description="`确定要删除选中的 ${selected.length} 条人员记录吗？删除后无法恢复。`"
        @confirm="onBatchDelete"
      >
        <Button variant="outline" size="sm" class="teacher-list__danger-btn">
          <Trash2 :size="18" /> 删除
        </Button>
      </DeleteConfirm>
      <Button variant="ghost" size="sm" @click="selected = []">取消选择</Button>
    </div>

    <DataTable
      :columns="columns"
      :data-source="data?.items ?? []"
      :row-key="(r) => r.id"
      :loading="isLoading"
      empty="没有符合条件的人员"
      selectable
      v-model:selected-keys="selected"
    >
      <template #cell="{ column, record }">
        <template v-if="column.key === 'name'">
          <RouterLink :to="`/teachers/${record.id}`" class="teacher-list__name-link">
            {{ record.name }}
          </RouterLink>
        </template>

        <template v-else-if="column.key === 'gender'">
          <span class="teacher-list__meta">{{ genderLabel[record.gender] ?? '—' }}</span>
        </template>

        <template v-else-if="column.key === 'age'">
          <span class="teacher-list__meta">{{ ageOrDash(record.age) }}</span>
        </template>

        <template v-else-if="column.key === 'subject'">
          <template v-if="record.subject">
            <span
              :class="cn('cat-pill', !categoryTint(subjectColor[record.subject]) && 'teacher-list__neutral-pill')"
              :style="categoryTint(subjectColor[record.subject]) ?? undefined"
            >
              {{ record.subject }}
            </span>
          </template>
          <span v-else class="teacher-list__muted">—</span>
        </template>

        <template v-else-if="column.key === 'has_cert'">
          <span :class="record.has_cert === 1 ? 'teacher-list__cert-yes' : 'teacher-list__cert-no'">
            {{ record.has_cert === 1 ? '有' : '无' }}
          </span>
        </template>

        <template v-else-if="column.key === 'phone'">
          <span v-if="record.phone" class="teacher-list__phone">{{ record.phone }}</span>
          <span v-else class="teacher-list__muted">—</span>
        </template>

        <template v-else-if="column.key === 'education'">
          <template v-if="record.education">{{ record.education }}</template>
          <span v-else class="teacher-list__muted">—</span>
        </template>

        <template v-else-if="column.key === 'university'">
          <span v-if="record.university" class="teacher-list__truncate" :title="record.university">
            {{ record.university }}
          </span>
          <span v-else class="teacher-list__muted">—</span>
        </template>

        <template v-else-if="column.key === 'major'">
          <span v-if="record.major" class="teacher-list__truncate" :title="record.major">
            {{ record.major }}
          </span>
          <span v-else class="teacher-list__muted">—</span>
        </template>

        <template v-else-if="column.key === 'created_at'">
          <span class="teacher-list__meta">{{ record.created_at }}</span>
        </template>

        <template v-else-if="column.key === 'action'">
          <div class="teacher-list__actions">
            <Button variant="ghost" size="sm" @click="router.push(`/teachers/${record.id}`)">
              查看
            </Button>
            <Button variant="ghost" size="icon" aria-label="编辑" @click="openEdit(record.id)">
              <Pencil :size="18" />
            </Button>
            <DeleteConfirm
              title="确认删除"
              :description="`确定要删除「${record.name}」吗？删除后无法恢复。`"
              @confirm="onDelete(record.id)"
            >
              <Button
                variant="ghost"
                size="icon"
                aria-label="删除"
                class="teacher-list__danger-btn"
              >
                <Trash2 :size="18" />
              </Button>
            </DeleteConfirm>
          </div>
        </template>
      </template>
    </DataTable>

    <PaginationBar
      :page="page"
      :page-size="PAGE_SIZE"
      :total="data?.total ?? 0"
      @change="(p) => (page = p)"
    />

    <TeacherFormDialog
      v-model:open="dialogOpen"
      :editing="editingId !== null ? editing ?? null : null"
      :subjects="subjects ?? []"
      :educations="educations ?? []"
      :submitting="formSubmitting"
      @submit="onSubmitDialog"
      @update:open="(v) => { if (!v) editingId = null }"
    />
  </div>
</template>

<style scoped>
.teacher-list {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.teacher-list__selection {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.75rem;
  border-radius: var(--r-thumb);
  padding: 10px 16px;
}
.teacher-list__selection-count {
  font-size: 14px;
  font-variant-numeric: tabular-nums;
  color: var(--text-2);
}
.teacher-list__danger-btn {
  color: var(--danger);
}
.teacher-list__danger-btn:hover {
  background: rgba(215, 0, 21, 0.08);
  color: var(--danger);
}

.teacher-list__name-link {
  font-weight: 500;
  color: var(--accent-link);
}
.teacher-list__name-link:hover {
  text-decoration: underline;
}

.teacher-list__neutral-pill {
  background: var(--track);
  color: var(--text-2);
}

.teacher-list__muted {
  color: var(--text-4);
}
.teacher-list__cert-yes {
  color: var(--accent-link);
}
.teacher-list__cert-no {
  color: var(--text-3);
}
.teacher-list__phone {
  font-family: var(--mono);
  font-size: 13px;
  font-variant-numeric: tabular-nums;
}
.teacher-list__meta {
  font-size: 13px;
  font-variant-numeric: tabular-nums;
  color: var(--text-2);
}
.teacher-list__truncate {
  display: block;
  max-width: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--text-2);
}
.teacher-list__actions {
  display: flex;
  align-items: center;
  gap: 2px;
}
</style>

// web/src/pages/TeacherList.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import {
  batchDeleteTeachers,
  createTeacher,
  deleteTeacher,
  exportXlsx,
  fetchTeacher,
  fetchTeachers,
  updateTeacher,
  ageOrDash,
  genderLabel,
  type ListParams,
  type Teacher,
  type TeacherInput,
} from '../api/teachers'
import { fetchDictionaries, type Dictionary } from '../api/dicts'
import TeacherFilters, { type TeacherFilterValues } from '@/components/teachers/TeacherFilters'
import TeacherFormDialog from '@/components/teachers/TeacherFormDialog'
import { Button } from '@/components/ui/button'
import { DataTable, PaginationBar, type Column } from '@/components/Table'
import PageHeader from '@/components/PageHeader'
import DeleteConfirm from '@/components/DeleteConfirm'
import { cn, categoryTint, errMsg } from '@/lib/utils'

const PAGE_SIZE = 20

export default function TeacherList() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [searchParams, setSearchParams] = useSearchParams()

  const urlKeyword = searchParams.get('keyword') ?? ''
  const [keyword, setKeyword] = useState(urlKeyword)
  const [debounced, setDebounced] = useState(urlKeyword)
  const [subject, setSubject] = useState(searchParams.get('subject') ?? '')
  const [gender, setGender] = useState<'' | 'male' | 'female'>(
    (searchParams.get('gender') as '' | 'male' | 'female') ?? '',
  )
  const [education, setEducation] = useState(searchParams.get('education') ?? '')
  const [hasCert, setHasCert] = useState<'' | '0' | '1'>(searchParams.get('hasCert') as '' | '0' | '1' ?? '')
  const [selected, setSelected] = useState<(string | number)[]>([])
  const [page, setPage] = useState(1)
  const [exporting, setExporting] = useState(false)

  // 新增 / 编辑弹窗：id 为 undefined 表示新增
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)

  const syncedKeywordRef = useRef<string | null>(null)

  useEffect(() => {
    if (urlKeyword === syncedKeywordRef.current) return
    setKeyword(urlKeyword)
    setPage(1)
  }, [urlKeyword])

  useEffect(() => {
    const t = setTimeout(() => setDebounced(keyword), 300)
    return () => clearTimeout(t)
  }, [keyword])

  // 关键字与筛选同步到 URL，刷新/分享后条件不丢
  useEffect(() => {
    syncedKeywordRef.current = debounced
    setSearchParams(
      (prev) => {
        const next = new URLSearchParams(prev)
        const setOrDel = (k: string, v: string) => {
          if (v) next.set(k, v)
          else next.delete(k)
        }
        setOrDel('keyword', debounced.trim())
        setOrDel('subject', subject)
        setOrDel('gender', gender)
        setOrDel('education', education)
        setOrDel('hasCert', hasCert)
        return next
      },
      { replace: true },
    )
  }, [debounced, subject, gender, education, hasCert, setSearchParams])

  useEffect(() => {
    setSelected([])
  }, [debounced, subject, gender, education, hasCert, page])

  const { data: subjects = [] } = useQuery({
    queryKey: ['dicts', 'subject'],
    queryFn: () => fetchDictionaries('subject'),
  })
  const { data: educations = [] } = useQuery({
    queryKey: ['dicts', 'education'],
    queryFn: () => fetchDictionaries('education'),
  })

  const subjectColor = useMemo(() => {
    const m: Record<string, string> = {}
    for (const d of subjects) if (d.color) m[d.name] = d.color
    return m
  }, [subjects])

  const listParams = useMemo<ListParams>(
    () => ({
      keyword: debounced.trim() || undefined,
      subject: subject || undefined,
      gender: gender || undefined,
      education: education || undefined,
      hasCert: (hasCert === '' ? '' : Number(hasCert)) as '' | 0 | 1,
    }),
    [debounced, subject, gender, education, hasCert],
  )

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['teachers', listParams, page],
    queryFn: () => fetchTeachers({ ...listParams, page, size: PAGE_SIZE }),
  })

  const { data: editing } = useQuery({
    queryKey: ['teachers', editingId],
    queryFn: () => fetchTeacher(editingId as number),
    enabled: editingId !== null,
  })

  const refresh = () => {
    refetch()
    queryClient.invalidateQueries({ queryKey: ['teachers'] })
  }

  const createMutation = useMutation({
    mutationFn: createTeacher,
    onSuccess: () => {
      toast.success('已创建')
      setDialogOpen(false)
      refresh()
    },
    onError: (e) => toast.error(errMsg(e, '创建失败')),
  })

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: TeacherInput }) => updateTeacher(id, data),
    onSuccess: () => {
      toast.success('已保存')
      setDialogOpen(false)
      setEditingId(null)
      refresh()
    },
    onError: (e) => toast.error(errMsg(e, '保存失败')),
  })

  const deleteMutation = useMutation({
    mutationFn: deleteTeacher,
    onSuccess: () => {
      toast.success('已删除')
      if ((data?.items.length ?? 0) === 1 && page > 1) setPage(page - 1)
      else refresh()
    },
    onError: (e) => toast.error(errMsg(e, '删除失败')),
  })

  const onExport = async () => {
    setExporting(true)
    try {
      await exportXlsx(listParams)
      toast.success('已导出 Excel')
    } catch (e) {
      toast.error(errMsg(e, '导出失败'))
    } finally {
      setExporting(false)
    }
  }

  const openCreate = () => {
    setEditingId(null)
    setDialogOpen(true)
  }

  const openEdit = (id: number) => {
    setEditingId(id)
    setDialogOpen(true)
  }

  const columns: Column<Teacher>[] = useMemo(
    () => [
      {
        title: '姓名',
        key: 'name',
        width: 120,
        render: (r) => (
          <Link
            to={`/teachers/${r.id}`}
            className="font-medium text-[var(--accent-link)] hover:underline"
          >
            {r.name}
          </Link>
        ),
      },
      {
        title: '性别',
        key: 'gender',
        width: 70,
        render: (r) => <span className="text-[var(--text-2)]">{genderLabel[r.gender] ?? '—'}</span>,
      },
      {
        title: '年龄',
        key: 'age',
        width: 70,
        render: (r) => <span className="tabular-nums text-[var(--text-2)]">{ageOrDash(r.age)}</span>,
      },
      {
        title: '学科',
        key: 'subject',
        width: 110,
        render: (r) => {
          if (!r.subject) return <span className="text-[var(--text-4)]">—</span>
          const tint = categoryTint(subjectColor[r.subject])
          return (
            <span
              className={cn(
                'inline-flex w-fit items-center rounded-full px-2.5 py-0.5 text-[12px] font-medium',
                tint ? 'cat-pill' : 'bg-[var(--track)] text-[var(--text-2)]',
              )}
              style={tint ?? undefined}
            >
              {r.subject}
            </span>
          )
        },
      },
      {
        title: '资格证',
        key: 'has_cert',
        width: 80,
        render: (r) => (
          <span className={r.has_cert === 1 ? 'text-[var(--accent-link)]' : 'text-[var(--text-3)]'}>
            {r.has_cert === 1 ? '有' : '无'}
          </span>
        ),
      },
      {
        title: '联系电话',
        key: 'phone',
        width: 130,
        render: (r) =>
          r.phone ? (
            <span className="font-mono text-[13px] tabular-nums">{r.phone}</span>
          ) : (
            <span className="text-[var(--text-4)]">—</span>
          ),
      },
      {
        title: '学历',
        key: 'education',
        width: 90,
        render: (r) =>
          r.education || <span className="text-[var(--text-4)]">—</span>,
      },
      {
        title: '毕业院校',
        key: 'university',
        render: (r) => (
          <span className="block max-w-[200px] truncate text-[var(--text-2)]" title={r.university}>
            {r.university || '—'}
          </span>
        ),
      },
      {
        title: '专业',
        key: 'major',
        render: (r) => (
          <span className="block max-w-[160px] truncate text-[var(--text-2)]" title={r.major}>
            {r.major || '—'}
          </span>
        ),
      },
      {
        title: '录入时间',
        key: 'created_at',
        width: 150,
        render: (r) => <span className="text-[13px] tabular-nums text-[var(--text-2)]">{r.created_at}</span>,
      },
      {
        title: '操作',
        key: 'action',
        width: 120,
        render: (r) => (
          <div className="flex items-center gap-0.5">
            <Button variant="ghost" size="icon" onClick={() => navigate(`/teachers/${r.id}`)} aria-label="查看">
              查看
            </Button>
            <Button variant="ghost" size="icon" onClick={() => openEdit(r.id)} aria-label="编辑">
              <Pencil />
            </Button>
            <DeleteConfirm
              title="确认删除"
              description={`确定要删除「${r.name}」吗？删除后无法恢复。`}
              trigger={
                <Button
                  variant="ghost"
                  size="icon"
                  className="text-destructive hover:bg-[rgba(215,0,21,0.08)] hover:text-destructive"
                  aria-label="删除"
                >
                  <Trash2 />
                </Button>
              }
              onConfirm={async () => {
                await deleteMutation.mutateAsync(r.id)
              }}
            />
          </div>
        ),
      },
    ],
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [subjectColor, navigate, data, page],
  )

  const onFilterChange = (next: Partial<Omit<TeacherFilterValues, 'keyword'>>) => {
    if (next.subject !== undefined) setSubject(next.subject)
    if (next.gender !== undefined) setGender(next.gender)
    if (next.education !== undefined) setEducation(next.education)
    if (next.hasCert !== undefined) setHasCert(next.hasCert)
    setPage(1)
  }

  const onSubmitDialog = async (input: TeacherInput) => {
    if (editingId) await updateMutation.mutateAsync({ id: editingId, data: input })
    else await createMutation.mutateAsync(input)
  }

  return (
    <div className="space-y-5">
      <PageHeader
        title="人员管理"
        description="学校教师与工作人员档案"
        action={
          <Button onClick={openCreate}>
            <Plus /> 新增人员
          </Button>
        }
      />

      <TeacherFilters
        keyword={keyword}
        onKeywordChange={(v) => {
          setKeyword(v)
          setPage(1)
        }}
        subjects={subjects.filter((d: Dictionary) => d.enabled === 1).map((d: Dictionary) => d.name)}
        educations={educations.filter((d: Dictionary) => d.enabled === 1).map((d: Dictionary) => d.name)}
        values={{ subject, gender, education, hasCert }}
        onChange={onFilterChange}
        onExport={onExport}
        exporting={exporting}
      />

      {selected.length > 0 && (
        <div className="flex flex-wrap items-center gap-3 surface-card rounded-[var(--r-thumb)] px-4 py-2.5">
          <span className="text-[14px] tabular-nums text-[var(--text-2)]">已选 {selected.length} 条</span>
          <DeleteConfirm
            title="批量删除"
            description={`确定要删除选中的 ${selected.length} 条人员记录吗？删除后无法恢复。`}
            trigger={
              <Button
                variant="outline"
                size="sm"
                className="text-destructive hover:bg-[rgba(215,0,21,0.06)] hover:text-destructive"
              >
                <Trash2 /> 删除
              </Button>
            }
            onConfirm={async () => {
              try {
                const n = await batchDeleteTeachers(selected.map(Number))
                toast.success(`已删除 ${n} 条记录`)
                setSelected([])
                refresh()
              } catch (e) {
                toast.error(errMsg(e, '批量删除失败'))
              }
            }}
          />
          <Button variant="ghost" size="sm" onClick={() => setSelected([])}>
            取消选择
          </Button>
        </div>
      )}

      <DataTable<Teacher>
        columns={columns}
        dataSource={data?.items ?? []}
        rowKey={(r) => r.id}
        loading={isLoading}
        empty="没有符合条件的人员"
        selectable
        selectedKeys={selected}
        onSelectedChange={setSelected}
      />

      <PaginationBar page={page} pageSize={PAGE_SIZE} total={data?.total ?? 0} onChange={setPage} />

      <TeacherFormDialog
        open={dialogOpen}
        onOpenChange={(open) => {
          setDialogOpen(open)
          if (!open) setEditingId(null)
        }}
        editing={editingId !== null ? editing ?? null : null}
        subjects={subjects}
        educations={educations}
        onSubmit={onSubmitDialog}
        submitting={createMutation.isPending || updateMutation.isPending}
      />
    </div>
  )
}
