// web/src/pages/TeacherDetail.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useParams } from 'react-router-dom'
import { useState, type ReactNode } from 'react'
import { toast } from 'sonner'
import { Pencil, Trash2 } from 'lucide-react'
import {
  deleteTeacher,
  fetchTeacher,
  updateTeacher,
  ageOrDash,
  genderLabel,
  type TeacherInput,
} from '@/api/teachers'
import { fetchDictionaries } from '@/api/dicts'
import PageHeader from '@/components/PageHeader'
import TeacherFormDialog from '@/components/teachers/TeacherFormDialog'
import DeleteConfirm from '@/components/DeleteConfirm'
import PageSpinner from '@/components/PageSpinner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { categoryTint, cn, errMsg } from '@/lib/utils'

function Field({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="flex gap-3 py-2">
      <span className="w-24 shrink-0 text-[14px] text-[var(--text-3)]">{label}</span>
      <span className="min-w-0 flex-1 break-words text-[14px] text-foreground">{value}</span>
    </div>
  )
}

export default function TeacherDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [editing, setEditing] = useState(false)

  const teacherId = Number(id)

  const { data: teacher, isLoading, error } = useQuery({
    queryKey: ['teachers', teacherId],
    queryFn: () => fetchTeacher(teacherId),
    enabled: Number.isInteger(teacherId) && teacherId > 0,
  })

  const { data: subjects = [] } = useQuery({
    queryKey: ['dicts', 'subject'],
    queryFn: () => fetchDictionaries('subject'),
  })
  const { data: educations = [] } = useQuery({
    queryKey: ['dicts', 'education'],
    queryFn: () => fetchDictionaries('education'),
  })

  const remove = useMutation({
    mutationFn: () => deleteTeacher(teacherId),
    onSuccess: () => {
      toast.success('已删除')
      queryClient.invalidateQueries({ queryKey: ['teachers'] })
      navigate('/', { replace: true })
    },
    onError: (e) => toast.error(errMsg(e, '删除失败')),
  })

  const update = useMutation({
    mutationFn: (input: TeacherInput) => updateTeacher(teacherId, input),
    onSuccess: (t) => {
      toast.success('已保存')
      queryClient.setQueryData(['teachers', teacherId], t)
      queryClient.invalidateQueries({ queryKey: ['teachers'] })
      setEditing(false)
    },
    onError: (e) => toast.error(errMsg(e, '保存失败')),
  })

  if (isLoading) return <PageSpinner />
  if (error || !teacher) {
    return (
      <div className="space-y-4 py-8 text-center">
        <p className="text-[15px] text-[var(--text-2)]">未找到该人员记录，可能已被删除</p>
        <Button variant="outline" onClick={() => navigate('/')}>
          返回列表
        </Button>
      </div>
    )
  }

  const subjectColor = subjects.find((d) => d.name === teacher.subject)?.color ?? ''
  const tint = categoryTint(subjectColor)

  return (
    <div className="space-y-5">
      <PageHeader
        onBack={() => navigate(-1)}
        title={teacher.name}
        description="人员档案详情"
        action={
          <>
            <Button variant="outline" onClick={() => setEditing(true)}>
              <Pencil /> 编辑
            </Button>
            <DeleteConfirm
              title="确认删除"
              description={`确定要删除「${teacher.name}」吗？删除后无法恢复。`}
              trigger={
                <Button
                  variant="outline"
                  className="text-destructive hover:bg-[rgba(215,0,21,0.06)] hover:text-destructive"
                >
                  <Trash2 /> 删除
                </Button>
              }
              onConfirm={async () => {
                await remove.mutateAsync()
              }}
            />
          </>
        }
      />

      <Card>
        <CardHeader>
          <CardTitle>基本信息</CardTitle>
        </CardHeader>
        <CardContent className="divide-y divide-[var(--hairline)]">
          <Field label="姓名" value={teacher.name} />
          <Field label="性别" value={genderLabel[teacher.gender] ?? '—'} />
          <Field label="年龄" value={<span className="tabular-nums">{ageOrDash(teacher.age)}</span>} />
          <Field
            label="学科"
            value={
              teacher.subject ? (
                <span
                  className={cn(
                    'inline-flex w-fit items-center rounded-full px-2.5 py-0.5 text-[12px] font-medium',
                    tint ? 'cat-pill' : 'bg-[var(--track)] text-[var(--text-2)]',
                  )}
                  style={tint ?? undefined}
                >
                  {teacher.subject}
                </span>
              ) : (
                '—'
              )
            }
          />
          <Field
            label="教师资格证"
            value={
              <span className={teacher.has_cert === 1 ? 'text-[var(--accent-link)]' : 'text-[var(--text-3)]'}>
                {teacher.has_cert === 1 ? '有' : '无'}
              </span>
            }
          />
          <Field
            label="联系电话"
            value={
              teacher.phone ? (
                <span className="font-mono tabular-nums">{teacher.phone}</span>
              ) : (
                '—'
              )
            }
          />
          <Field label="学历" value={teacher.education || '—'} />
          <Field label="毕业院校" value={teacher.university || '—'} />
          <Field label="专业" value={teacher.major || '—'} />
          <Field label="备注" value={teacher.remark || '—'} />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>时间</CardTitle>
        </CardHeader>
        <CardContent className="divide-y divide-[var(--hairline)]">
          <Field label="录入时间" value={<span className="tabular-nums">{teacher.created_at}</span>} />
          <Field label="更新时间" value={<span className="tabular-nums">{teacher.updated_at}</span>} />
        </CardContent>
      </Card>

      <TeacherFormDialog
        open={editing}
        onOpenChange={setEditing}
        editing={teacher}
        subjects={subjects}
        educations={educations}
        onSubmit={async (input) => {
          await update.mutateAsync(input)
        }}
        submitting={update.isPending}
      />
    </div>
  )
}

// web/src/pages/TeacherDetail.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Pencil, Trash2 } from 'lucide-vue-next'
import {
  deleteTeacher,
  fetchTeacher,
  updateTeacher,
  ageOrDash,
  genderLabel,
  type TeacherInput,
} from '@/api/teachers'
import { fetchDictionaries } from '@/api/dicts'
import PageHeader from '@/components/PageHeader.vue'
import TeacherFormDialog from '@/components/teachers/TeacherFormDialog.vue'
import DeleteConfirm from '@/components/DeleteConfirm.vue'
import PageSpinner from '@/components/PageSpinner.vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardTitle from '@/components/ui/CardTitle.vue'
import CardContent from '@/components/ui/CardContent.vue'
import { useQuery, useMutation, invalidateQueries, setQueryData } from '@/composables/useQuery'
import { useToast } from '@/composables/useToast'
import { categoryTint, cn, errMsg } from '@/lib/utils'

const route = useRoute()
const router = useRouter()
const { success, error } = useToast()
const editing = ref(false)

const teacherId = Number(route.params.id)

const { data: teacher, isLoading, error: loadError } = useQuery(
  ['teachers', teacherId],
  () => fetchTeacher(teacherId),
  { enabled: computed(() => Number.isInteger(teacherId) && teacherId > 0) },
)

const { data: subjects } = useQuery<import('@/api/dicts').Dictionary[]>(['dicts', 'subject'], () =>
  fetchDictionaries('subject'),
)
const { data: educations } = useQuery<import('@/api/dicts').Dictionary[]>(
  ['dicts', 'education'],
  () => fetchDictionaries('education'),
)

const remove = useMutation(() => deleteTeacher(teacherId))
const update = useMutation((input: TeacherInput) => updateTeacher(teacherId, input))
const updatePending = update.isPending

const onDelete = async () => {
  try {
    await remove.mutate()
    success('已删除')
    invalidateQueries(['teachers'])
    void router.replace('/')
  } catch (e) {
    error(errMsg(e, '删除失败'))
  }
}

const onUpdate = async (input: TeacherInput) => {
  try {
    const t = await update.mutate(input)
    success('已保存')
    setQueryData(['teachers', teacherId], t)
    invalidateQueries(['teachers'])
    editing.value = false
  } catch (e) {
    error(errMsg(e, '保存失败'))
  }
}

const subjectColor = computed(() => {
  const d = (subjects.value ?? []).find((x) => x.name === teacher.value?.subject)
  return d?.color ?? ''
})
const tint = computed(() => categoryTint(subjectColor.value))
</script>

<template>
  <div v-if="isLoading" class="teacher-detail">
    <PageSpinner />
  </div>

  <div v-else-if="loadError || !teacher" class="teacher-detail teacher-detail__not-found">
    <p class="teacher-detail__not-found-text">未找到该人员记录，可能已被删除</p>
    <Button variant="outline" @click="router.push('/')">返回列表</Button>
  </div>

  <div v-else class="teacher-detail">
    <PageHeader :title="teacher.name" description="人员档案详情" @back="router.back()">
      <template #action>
        <Button variant="outline" @click="editing = true">
          <Pencil :size="18" /> 编辑
        </Button>
        <DeleteConfirm
          title="确认删除"
          :description="`确定要删除「${teacher.name}」吗？删除后无法恢复。`"
          @confirm="onDelete"
        >
          <Button variant="outline" class="teacher-detail__danger-btn">
            <Trash2 :size="18" /> 删除
          </Button>
        </DeleteConfirm>
      </template>
    </PageHeader>

    <Card>
      <CardHeader>
        <CardTitle>基本信息</CardTitle>
      </CardHeader>
      <CardContent class="teacher-detail__fields">
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">姓名</span>
          <span class="teacher-detail__value">{{ teacher.name }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">性别</span>
          <span class="teacher-detail__value">{{ genderLabel[teacher.gender] ?? '—' }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">年龄</span>
          <span class="teacher-detail__value tabular-nums">{{ ageOrDash(teacher.age) }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">学科</span>
          <span class="teacher-detail__value">
            <span
              v-if="teacher.subject"
              :class="cn('cat-pill', !tint && 'teacher-detail__neutral-pill')"
              :style="tint ?? undefined"
            >
              {{ teacher.subject }}
            </span>
            <span v-else>—</span>
          </span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">教师资格证</span>
          <span
            :class="teacher.has_cert === 1 ? 'teacher-detail__cert-yes' : 'teacher-detail__cert-no'"
          >
            {{ teacher.has_cert === 1 ? '有' : '无' }}
          </span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">联系电话</span>
          <span v-if="teacher.phone" class="teacher-detail__phone">{{ teacher.phone }}</span>
          <span v-else>—</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">学历</span>
          <span class="teacher-detail__value">{{ teacher.education || '—' }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">毕业院校</span>
          <span class="teacher-detail__value">{{ teacher.university || '—' }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">专业</span>
          <span class="teacher-detail__value">{{ teacher.major || '—' }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">备注</span>
          <span class="teacher-detail__value">{{ teacher.remark || '—' }}</span>
        </div>
      </CardContent>
    </Card>

    <Card>
      <CardHeader>
        <CardTitle>时间</CardTitle>
      </CardHeader>
      <CardContent class="teacher-detail__fields">
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">录入时间</span>
          <span class="teacher-detail__value tabular-nums">{{ teacher.created_at }}</span>
        </div>
        <div class="teacher-detail__field">
          <span class="teacher-detail__label">更新时间</span>
          <span class="teacher-detail__value tabular-nums">{{ teacher.updated_at }}</span>
        </div>
      </CardContent>
    </Card>

    <TeacherFormDialog
      v-model:open="editing"
      :editing="teacher"
      :subjects="subjects ?? []"
      :educations="educations ?? []"
      :submitting="updatePending"
      @submit="onUpdate"
    />
  </div>
</template>

<style scoped>
.teacher-detail {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}
.teacher-detail__not-found {
  align-items: center;
  padding: 32px 0;
  text-align: center;
}
.teacher-detail__not-found-text {
  font-size: 15px;
  color: var(--text-2);
}
.teacher-detail__danger-btn {
  color: var(--danger);
}
.teacher-detail__danger-btn:hover {
  background: rgba(215, 0, 21, 0.06);
  color: var(--danger);
}

.teacher-detail__fields {
  display: flex;
  flex-direction: column;
}
.teacher-detail__field {
  display: flex;
  gap: 0.75rem;
  padding: 8px 0;
  border-bottom: 1px solid var(--hairline);
}
.teacher-detail__field:last-child {
  border-bottom: 0;
}
.teacher-detail__label {
  width: 96px;
  flex-shrink: 0;
  font-size: 14px;
  color: var(--text-3);
}
.teacher-detail__value {
  min-width: 0;
  flex: 1;
  font-size: 14px;
  color: var(--text);
  word-break: break-word;
}
.teacher-detail__neutral-pill {
  background: var(--track);
  color: var(--text-2);
}
.teacher-detail__cert-yes {
  color: var(--accent-link);
}
.teacher-detail__cert-no {
  color: var(--text-3);
}
.teacher-detail__phone {
  font-family: var(--mono);
  font-variant-numeric: tabular-nums;
}
</style>
