// web/src/components/DeleteConfirm.vue
<script setup lang="ts">
import { ref } from 'vue'
import Button from '@/components/ui/Button.vue'
import Dialog from '@/components/ui/Dialog.vue'
import DialogHeader from '@/components/ui/DialogHeader.vue'
import DialogTitle from '@/components/ui/DialogTitle.vue'
import DialogDescription from '@/components/ui/DialogDescription.vue'
import DialogFooter from '@/components/ui/DialogFooter.vue'
import { useToast } from '@/composables/useToast'
import { errMsg } from '@/lib/utils'

withDefaults(
  defineProps<{
    title: string
    description: string
    confirmLabel?: string
  }>(),
  { confirmLabel: '删除' },
)

const emit = defineEmits<{ confirm: [] }>()

const { error } = useToast()
const open = ref(false)
const loading = ref(false)

async function handleConfirm() {
  loading.value = true
  try {
    await emit('confirm')
    open.value = false
  } catch (e) {
    error(errMsg(e, '操作失败'))
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <span @click.stop="open = true">
    <slot />
  </span>

  <Dialog v-model:open="open">
    <DialogHeader>
      <DialogTitle>{{ title }}</DialogTitle>
      <DialogDescription v-if="description">{{ description }}</DialogDescription>
    </DialogHeader>
    <DialogFooter>
      <Button variant="outline" :disabled="loading" @click="open = false">取消</Button>
      <Button variant="destructive" :loading="loading" @click="handleConfirm">
        {{ confirmLabel }}
      </Button>
    </DialogFooter>
  </Dialog>
</template>

// web/src/components/DeleteConfirm.tsx
import { useState, type ReactNode } from 'react'
import { toast } from 'sonner'
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { errMsg } from '@/lib/utils'

export default function DeleteConfirm({
  title,
  description,
  trigger,
  onConfirm,
}: {
  title: string
  description: string
  trigger: ReactNode
  onConfirm: () => Promise<void> | void
}) {
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleConfirm = async () => {
    setLoading(true)
    try {
      await onConfirm()
      setOpen(false)
    } catch (e) {
      toast.error(errMsg(e, '操作失败'))
    } finally {
      setLoading(false)
    }
  }

  return (
    <AlertDialog open={open} onOpenChange={setOpen}>
      <AlertDialogTrigger asChild>{trigger}</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{title}</AlertDialogTitle>
          {description && <AlertDialogDescription>{description}</AlertDialogDescription>}
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={loading}>{'取消'}</AlertDialogCancel>
          {/* 不使用 AlertDialogAction：避免 Radix 点击即关闭，操作失败时保持弹窗打开 */}
          <Button variant="destructive" loading={loading} onClick={() => void handleConfirm()}>
            删除
          </Button>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
